sudo: required
services:
  - docker

before_install:
  - docker build -t anka86/react-test -f ./client/Dockerfile.dev ./client

script:
  #- docker run anka86/react-test npm test -- --coverage
  - docker run -e CI=true anka86/react-test npm test

# tells travis to build app images instead of Elastic Beanstalk, if no errors has come!
after_success:
  - docker build -t anka86/multi-client ./client
  - docker build -t anka86/multi-nginx ./nginx
  - docker build -t anka86/multi-server ./server
  - docker build -t anka86/multi-worker ./worker
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take those images and push them to docker hub
  - docker push anka86/multi-client
  - docker push anka86/multi-nginx
  - docker push anka86/multi-server
  - docker push anka86/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "udemy-multi-docker"
  env: "UdemyMultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-483017516015"
  bucket_path: "docker-multi"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY