sudo: required
services:
  - docker

before_install:
  - docker build -t anka86/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run anka86/react-test npm test -- --coverage

# tells travis to build app images instead of Elastic Beanstalk, if no errors has come!
after_success:
  - docker build -t anka86/multi-client ./client
  - docker build -t anka86/multi-nginx ./nginx
  - docker build -t anka86/multi-server ./server
  - docker build -t anka86/multi-worker ./worker
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take those images and push them to docker hub
  - docker push anka86/multi-client
  - docker push anka86/multi-nginx
  - docker push anka86/multi-server
  - docker push anka86/multi-worker